# Generated by Django 2.2 on 2019-04-02 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pubsub', '0002_category_publisher_subscribeoption_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='hero/'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='logo_image',
            field=models.ImageField(blank=True, null=True, upload_to='logo/'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='sub_categories',
            field=models.ManyToManyField(related_name='sub_categories', to='pubsub.Category'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='pubsub.Category'),
        ),
    ]
