# Generated by Django 2.2 on 2019-04-02 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubsub', '0003_auto_20190402_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='sub_categories',
            field=models.ManyToManyField(blank=True, related_name='sub_categories', to='pubsub.Category'),
        ),
    ]
