# Generated by Django 2.2 on 2019-04-03 06:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pubsub', '0004_auto_20190402_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='end',
            field=models.DateField(blank=True, help_text='When subscription ends', null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='start',
            field=models.DateField(blank=True, help_text='When subscription begins', null=True),
        ),
    ]
